enum AgentStatuses {
  ACTIVATED = "ACTIVATED",
  ARCHIVED = "ARCHIVED",
  DECLINED = "DECLINED",
  PENDING = "PENDING",
  DEACTIVATED = "DEACTIVATED",
  DELETE = "DELETE",
}

export { AgentStatuses };
