export type AgentData = {
  _id: string;
  name: string;
  userGuid: string;
  avatar: string;
  title: string;
  bio: string;
  phoneNumber: string;
  emailAddress: string;
  address: string;
  twitter: string;
  instagram: string;
  linkedIn: string;
  facebook: string;
  password: string;
  languages?: string[];
  role: string;
  status: string;
  telNumber: string;
  webinars: string[];
  specialties?: string[];
  isDeclined: false;
  createdAt: string;
  updatedAt: string;
  testimonials?: string[];
  calendlyLink: string;
};
