export const BEARER = "Bearer";
export const BLANK_VALUE = "—";

export const ROLES = {
  ROLE_AGENT: "ROLE_AGENT",
  ROLE_MASTER_ADMIN: "ROLE_MASTER_ADMIN",
};

export const AGENT_STATUSES = {
  ACTIVATED: "ACTIVATED",
  DECLINED: "DECLINED",
  PENDING: "PENDING",
  DEACTIVATED: "DEACTIVATED",
};
