export const BEARER = "Bearer";
export const BLANK_VALUE = "—";

export const ROLES = {
  ROLE_AGENT: "ROLE_AGENT",
  ROLE_MASTER_ADMIN: "ROLE_MASTER_ADMIN",
};

export const AGENT_STATUSES = {
  ACTIVATED: "ACTIVATED",
  DECLINED: "DECLINED",
  PENDING: "PENDING",
  DEACTIVATED: "DEACTIVATED",
};

export const AGENT_SPECIALTIES = {
  WEALTH_BUILDER: "WEALTH BUILDER",
  FINANCIAL_FREEDOM: "FINANCIAL_FREEDOM",
  LEGACY_BUILDER: "LEGACY_BUILDER",
  LONG_TERM_CARE: "LONG_TERM_CARE",
};
