export const BEARER = "Bearer";
export const BLANK_VALUE = "—";

export const ROLES = {
  ROLE_AGENT: "ROLE_AGENT",
  ROLE_MASTER_ADMIN: "ROLE_MASTER_ADMIN",
  ROLE_EDITOR: "ROLE_EDITOR",
};

export const AGENT_STATUSES = {
  ACTIVATED: "ACTIVATED",
  DECLINED: "DECLINED",
  PENDING: "PENDING",
  DEACTIVATED: "DEACTIVATED",
};

export const AGENT_SPECIALTIES = [
  "Wealth Builder",
  "Financial Freedom",
  "Long Term Care",
  "Legacy Builder",
];

export const APPOINTMENT_TYPES = {
  WEBINAR: "WEBINAR",
  PAW: "PAW",
};

export const APPOINTMENT_STATUSES = {
  CANCELLED: "CANCELLED",
  ACTIVE: "ACTIVE",
  ONGOING: "ONGOING",
};

export const NOTIFICATION_ENUMS = {
  WEBINARS: {
    WEBINAR_REQUEST: "WEBINAR_REQUEST",
    WEBINAR_DECLINED: "WEBINAR_DECLINED",
    WEBINAR_APPROVED: "WEBINAR_APPROVED",
  },
  APPOINTMENTS: {
    APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
    APPOINTMENT_NEW: "APPOINTMENT_NEW",
  },
  BLOGS: {
    BLOGS_REQUEST: "BLOGS_REQUEST",
    BLOGS_DRAFT: "BLOGS_DRAFT",
    BLOGS_PUBLISHED: "BLOGS_PUBLISHED",
    BLOGS_DECLINED: "BLOGS_DECLINED",
  },
};
